"""Storage interface independent of SQL driver and inference transport."""
from typing import Protocol


class StorageError(RuntimeError):
    """Safe public error; never contains driver credentials or SQL parameters."""


class JobRepository(Protocol):
    def create(self, total: int, input_timezone: str) -> dict: ...
    def finish(self, job_id: str, results: list) -> dict: ...
    def get(self, job_id: str) -> dict: ...
    def list_jobs(self, limit: int = 50) -> list: ...
    def import_job(self, document: dict) -> bool: ...
